In [22]:
import numpy as np 
import pandas as pd 

deid_data = pd.read_csv('/Users/bellalu/Desktop/Alonzi_CJDTI_2025-2026/ForecastBedData/cvrj_dataset_v2.csv')
deid_data

,Booking #,Sex,Race,Age,Book Date,Unnamed: 5,Release Date,Length of Stay,County Code,Release Authority,Offense Code,Offense Description
0,2011-02736,F,W,40,1/13/2012 8:00:00 PM,1/0/1900 12:00:00 AM,1/14/2012 8:00:00 PM,1.00,109,TIME SERVED,DWI5453M1,TRAFFIC - DRIVING WHILE INTOXICATED - FIRST - ...
1,2011-03139,M,W,47,1/1/2012 9:00:00 AM,1/0/1900 12:00:00 AM,1/4/2012 9:00:00 AM,3.00,109,TIME SERVED,STK2109M1,EXTORTION WITH INTENT TO CAUSE FEAR OF DEATH -...
2,2011-03184,F,W,21,1/6/2012 4:00:00 PM,1/0/1900 12:00:00 AM,1/8/2012 4:00:00 PM,2.00,109,JUDGE,ASL1313M1,ASSAULT SIMPLE ASSAULT
3,2011-03441,M,W,35,1/13/2012 6:00:00 PM,1/0/1900 12:00:00 AM,1/15/2012 6:00:00 PM,2.00,109,TIME SERVED,REC6648M1,TRAFFIC - RECKLESS DRIVING SPEED OVER 80 MPH
4,2011-03463,M,B,45,9/2/2012 6:00:00 PM,1/0/1900 12:00:00 AM,10/15/2012 8:00:00 AM,42.58,79,TIME SERVED,DES3237M1,DESERTION AND NONSUPPORT FAIL TO COMPLY WITH S...
...,...,...,...,...,...,...,...,...,...,...,...,...
46122,2025-03420,M,W,32,12/31/2025 9:51:00 AM,0,1/14/2026 10:23:00 AM,0.588888889,47,JUDGE,LAR2359F9,LARCENY $1000 OR MORE NOT FROM PERSON
46123,2025-03421,M,W,30,12/31/2025 10:46:00 AM,0,1/14/2026 3:38:00 PM,0.550694444,139,JUDGE,PRB4850F9,"PAROLE, PROBATION, SUPERVISION VIOLATION PROBA..."
46124,2025-03422,M,W,19,12/31/2025 10:46:00 AM,0,1/7/2026 7:30:00 PM,0.550694444,139,JUDGE,PRB4850F9,"PAROLE, PROBATION, SUPERVISION VIOLATION PROBA..."
46125,2025-03423,F,W,35,12/31/2025 5:15:00 PM,0,1/8/2026 9:10:00 PM,0.280555556,137,BOND,EXT2106F6,"EXT-THREAT BY LETTER,COMMUNICATION,OR ELECTRON..."
46126,2025-03424,M,W,37,12/31/2025 11:29:00 PM,0,1/1/2026 1:39:00 PM,0.020833333,79,BOND,OBS3712M4,"DRUNK IN PUBLIC, INTOX. FROM DRUG"

In [23]:
deid_data = deid_data[~deid_data['Booking #'].str.contains('2011')]
deid_data

,Booking #,Sex,Race,Age,Book Date,Unnamed: 5,Release Date,Length of Stay,County Code,Release Authority,Offense Code,Offense Description
16,2012-00002,M,W,39,1/1/2012 2:52:00 AM,1/0/1900 12:00:00 AM,1/1/2012 7:15:00 AM,1.00,109,BOND,OBS3712M4,OBSCENITY DRUNK IN PUBLIC - PROFANE LANGUAGE
17,2012-00003,M,W,49,1/1/2012 2:52:00 AM,1/0/1900 12:00:00 AM,1/1/2012 10:24:00 AM,1.00,109,BOND,ASL1315M1,ASSAULT SIMPLE ASSAULT - AGAINST FAMILY MEMBER
18,2012-00004,M,B,23,1/1/2012 3:01:00 AM,1/0/1900 12:00:00 AM,1/6/2012 3:40:00 PM,5.53,109,BOND,KID1010F5,KIDNAPPING ABDUCT BY FORCE WITHOUT JUSTIFICATION
19,2012-00005,F,B,31,1/1/2012 3:11:00 AM,1/0/1900 12:00:00 AM,1/1/2012 10:53:00 AM,1.00,65,BOND,DWI5443M1,TRAFFIC - DRIVING WHILE INTOXICATED - FIRST - ...
20,2012-00006,M,W,31,1/1/2012 2:55:00 AM,1/0/1900 12:00:00 AM,1/1/2012 10:16:51 AM,1.00,137,BOND,ASL1313M1,ASSAULT SIMPLE ASSAULT
...,...,...,...,...,...,...,...,...,...,...,...,...
46122,2025-03420,M,W,32,12/31/2025 9:51:00 AM,0,1/14/2026 10:23:00 AM,0.588888889,47,JUDGE,LAR2359F9,LARCENY $1000 OR MORE NOT FROM PERSON
46123,2025-03421,M,W,30,12/31/2025 10:46:00 AM,0,1/14/2026 3:38:00 PM,0.550694444,139,JUDGE,PRB4850F9,"PAROLE, PROBATION, SUPERVISION VIOLATION PROBA..."
46124,2025-03422,M,W,19,12/31/2025 10:46:00 AM,0,1/7/2026 7:30:00 PM,0.550694444,139,JUDGE,PRB4850F9,"PAROLE, PROBATION, SUPERVISION VIOLATION PROBA..."
46125,2025-03423,F,W,35,12/31/2025 5:15:00 PM,0,1/8/2026 9:10:00 PM,0.280555556,137,BOND,EXT2106F6,"EXT-THREAT BY LETTER,COMMUNICATION,OR ELECTRON..."
46126,2025-03424,M,W,37,12/31/2025 11:29:00 PM,0,1/1/2026 1:39:00 PM,0.020833333,79,BOND,OBS3712M4,"DRUNK IN PUBLIC, INTOX. FROM DRUG"

In [24]:
orange_pop = pd.read_csv('/Users/bellalu/Desktop/Alonzi_CJDTI_2025-2026/ForecastBedData/OrangePopulation.csv', skiprows = 4)
madison_pop = pd.read_csv('/Users/bellalu/Desktop/Alonzi_CJDTI_2025-2026/ForecastBedData/MadisonPopulation.csv', skiprows = 4)
greene_pop = pd.read_csv('/Users/bellalu/Desktop/Alonzi_CJDTI_2025-2026/ForecastBedData/GreenePopulation.csv', skiprows = 4)
louisa_pop = pd.read_csv('/Users/bellalu/Desktop/Alonzi_CJDTI_2025-2026/ForecastBedData/LouisaPopulation.csv', skiprows = 4)
fluvanna_pop = pd.read_csv('/Users/bellalu/Desktop/Alonzi_CJDTI_2025-2026/ForecastBedData/FluvannaPopulation.csv', skiprows = 4)
culpeper_pop = pd.read_csv('/Users/bellalu/Desktop/Alonzi_CJDTI_2025-2026/ForecastBedData/CulpeperPopulation.csv', skiprows = 4)
page_pop = pd.read_csv('/Users/bellalu/Desktop/Alonzi_CJDTI_2025-2026/ForecastBedData/PagePopulation.csv', skiprows = 4)

In [25]:
orange_pop = orange_pop.drop(index = [0])
madison_pop = madison_pop.drop(index = [0])
greene_pop = greene_pop.drop(index = [0])
louisa_pop = louisa_pop.drop(index = [0])
fluvanna_pop = fluvanna_pop.drop(index = [0])
culpeper_pop = culpeper_pop.drop(index = [0])
page_pop = page_pop.drop(index = [0])

In [ ]:
monthly_adp = pd.read_excel('/Users/bellalu/Desktop/Alonzi_CJDTI_2025-2026/ForecastBedData/MonthlyADP202511.xlsx')
#ask about monthly adp

,Jail Num,Cost Code,JailName,Date by Month,Pre-Trial Probation Violators,Pre-Trial Parole Violators,Other Pretrial,Total Pretrial Pop,Awaiting Trial w/SR Sent,Awaiting Trial w/LR Sent,...,SR Felons,Federal,Contract,Military,Juvenile,LR Male,LR Female,SR Male,SR Female,Total ADP
0,1,1,Accomack County Jail,2025/11,17.87,0.00,40.53,58.40,2.57,13.17,...,18.60,0.00,0,0.0,0,73.53,9.17,15.77,2.83,101.43
1,3,405,Albemarle-Charlottesville Regional Jail,2025/11,32.50,0.00,144.20,176.70,19.17,22.87,...,44.43,19.80,0,0.0,0,216.30,28.23,42.93,1.50,310.50
2,5,5,Alleghany Regional Jail,2025/11,11.00,0.00,37.57,48.57,0.47,3.50,...,15.07,0.00,0,0.0,0,48.80,11.23,14.07,1.00,76.47
3,10,485,BRRJ Amherst ADC,2025/11,29.70,0.00,149.33,179.03,18.33,44.33,...,89.70,2.30,0,0.0,0,241.67,53.37,78.47,11.23,390.40
4,13,13,Arlington County Detention Center,2025/11,36.43,0.00,172.00,208.43,8.77,35.00,...,41.90,0.43,0,0.0,0,254.60,21.03,39.90,2.00,320.13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,710,710,Norfolk City Jail,2025/11,67.57,1.00,361.67,430.24,22.40,27.57,...,155.43,10.73,0,0.0,0,488.77,68.77,150.10,5.33,732.69
60,740,740,Portsmouth City Jail,2025/11,19.00,1.00,101.67,121.67,8.17,13.13,...,10.20,0.00,0,0.0,0,143.57,19.60,8.77,1.43,173.63
61,760,760,Richmond City Jail,2025/11,77.03,3.93,299.93,380.89,20.40,55.00,...,130.63,0.10,0,0.0,0,452.07,47.97,123.57,7.07,634.53
62,770,770,Roanoke City Jail,2025/11,19.70,1.37,179.30,200.37,10.03,32.93,...,33.10,37.37,0,0.0,0,235.53,41.50,31.50,1.60,347.50
63,810,810,Virginia Beach City Jail,2025/11,123.20,1.47,603.77,728.44,36.20,46.10,...,196.93,4.10,0,0.0,0,741.90,154.83,180.53,16.40,1104.00

## Forecast Model Implementation
The following code processes the raw booking data to calculate ADP, loads census data, and performs SARIMA forecasting.

In [ ]:

import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
import matplotlib.pyplot as plt
import os

# --- Configuration ---
# Update paths to be relative to the notebook or absolute
# Assuming notebook is in cvrj-bed-forecasting/ForecastBedData/
DATA_DIR = "." 
CVRJ_FILE = "cvrj_dataset_v2.csv" # In same dir as notebook usually or parent?
# Check specific file location:
if not os.path.exists(CVRJ_FILE):
    # Try absolute path if relative fails, or parent
    CVRJ_FILE = "../cvrj_dataset_v2.csv"
    DATA_DIR = "."

print(f"Using CVRJ File: {CVRJ_FILE}")

# --- 1. Load and Process CVRJ Data ---
df_cvrj = pd.read_csv(CVRJ_FILE)
df_cvrj['Book Date'] = pd.to_datetime(df_cvrj['Book Date'], errors='coerce')
df_cvrj['Release Date'] = pd.to_datetime(df_cvrj['Release Date'], errors='coerce')

# Filter for relevant years (2012-2025)
df_cvrj = df_cvrj[df_cvrj['Book Date'].dt.year >= 2012]

# Calculate Daily Census (ADP)
min_date = df_cvrj['Book Date'].min()
max_date = df_cvrj['Release Date'].max()
if pd.isnull(max_date) or max_date.year > 2030: 
    max_date = pd.Timestamp('2025-12-31')

date_range = pd.date_range(start=min_date.normalize(), end=max_date.normalize(), freq='D')

events = []
for _, row in df_cvrj.iterrows():
    start = row['Book Date']
    end = row['Release Date']
    if pd.isnull(start): continue
    if pd.isnull(end): end = max_date
    start_date = start.normalize()
    end_date = end.normalize()
    if end_date < start_date: continue
    events.append((start_date, 1))
    events.append((end_date + pd.Timedelta(days=1), -1))

evt_df = pd.DataFrame(events, columns=['Date', 'Change'])
if not evt_df.empty:
    evt_df = evt_df.groupby('Date')['Change'].sum().sort_index()
    daily_census = evt_df.reindex(date_range, fill_value=0).cumsum()
else:
    daily_census = pd.Series(0, index=date_range)

# Aggregating to Annual ADP
annual_cvrj_adp = daily_census.resample('Y').mean()
print("CVRJ Annual ADP (Head):")
print(annual_cvrj_adp.head())

# --- 2. Load Population Data ---
counties = ['Fluvanna', 'Greene', 'Louisa', 'Madison', 'Orange']
pop_data = {}

for county in counties:
    fpath = os.path.join(DATA_DIR, f"{county}Population.csv")
    try:
        if os.path.exists(fpath):
            temp_df = pd.read_csv(fpath, header=4)
            target_row = temp_df.iloc[1]
            years = [str(y) for y in range(2012, 2025)]
            pop_series = target_row[years].str.replace(',', '').astype(float)
            pop_series.index = pd.to_datetime(pop_series.index, format='%Y')
            pop_data[county] = pop_series
        else:
            print(f"Warning: {fpath} not found.")
    except Exception as e:
        print(f"Error loading {county}: {e}")

if pop_data:
    total_cvrj_pop = pd.DataFrame(pop_data).sum(axis=1)
    total_cvrj_pop.index = total_cvrj_pop.index + pd.offsets.YearEnd()
else:
    total_cvrj_pop = pd.Series()

# --- 3. Load Culpeper Data ---
culpeper_data = {
    '2020': 148.93, '2021': 185.75, '2022': 210.82, 
    '2023': 200.24, '2024': 312.33, '2025': 227.81
}
culpeper_adp = pd.Series(culpeper_data)
culpeper_adp.index = pd.to_datetime(culpeper_adp.index, format='%Y') + pd.offsets.YearEnd()

# Culpeper Census
culp_pop_file = os.path.join(DATA_DIR, "CulpeperPopulation.csv")
culp_pop = pd.Series()
if os.path.exists(culp_pop_file):
    try:
        temp_culp = pd.read_csv(culp_pop_file, header=4)
        culp_pop_row = temp_culp.iloc[1]
        years = [str(y) for y in range(2012, 2025)]
        culp_pop = culp_pop_row[years].str.replace(',', '').astype(float)
        culp_pop.index = pd.to_datetime(culp_pop.index, format='%Y') + pd.offsets.YearEnd()
    except Exception as e:
        print(f"Error loading Culpeper Census: {e}")

# --- 4. SARIMA Modeling & Forecasting ---

def fit_forecast(adp_series, exog_series, name, steps=10):
    print(f"\nModeling {name}...")
    combined = pd.concat([adp_series, exog_series], axis=1).dropna()
    combined.columns = ['ADP', 'Pop']
    
    if combined.empty:
        print(f"Empty training data for {name}")
        return None, None
        
    try:
        model = SARIMAX(combined['ADP'], exog=combined['Pop'], order=(1,1,1), seasonal_order=(0,0,0,0))
        results = model.fit(disp=False)
        print(results.summary())
        
        # Forecast Population (Linear Trend)
        pop_y = combined['Pop'].values
        pop_x = np.arange(len(pop_y))
        z = np.polyfit(pop_x, pop_y, 1)
        p = np.poly1d(z)
        future_x = np.arange(len(pop_y), len(pop_y) + steps)
        future_pop = p(future_x)
        
        forecast = results.get_forecast(steps=steps, exog=future_pop.reshape(-1,1))
        forecast_vals = forecast.predicted_mean
        return forecast_vals, future_pop
    except Exception as e:
        print(f"Error modeling {name}: {e}")
        return None, None

# Model CVRJ
if not total_cvrj_pop.empty:
    # Extrapolate Pop 2025
    last_pop = total_cvrj_pop.iloc[-1]
    prev_pop = total_cvrj_pop.iloc[-2]
    total_cvrj_pop.loc[pd.Timestamp('2025-12-31')] = last_pop + (last_pop - prev_pop)

cvrj_forecast, cvrj_fut_pop = fit_forecast(annual_cvrj_adp, total_cvrj_pop, "CVRJ")

# Model Culpeper
if not culp_pop.empty:
    last_c_pop = culp_pop.iloc[-1]
    prev_c_pop = culp_pop.iloc[-2]
    culp_pop.loc[pd.Timestamp('2025-12-31')] = last_c_pop + (last_c_pop - prev_c_pop)

culpeper_clean = culpeper_adp[~culpeper_adp.index.year.isin([2020, 2021])]
culpeper_forecast, culp_fut_pop = fit_forecast(culpeper_clean, culp_pop, "Culpeper")

# --- 5. Visualization ---
if cvrj_forecast is not None and culpeper_forecast is not None:
    years_future = pd.date_range(start='2026-12-31', periods=10, freq='Y')
    res_df = pd.DataFrame({
        'CVRJ_Baseline': cvrj_forecast.values,
        'Culpeper_Add': culpeper_forecast.values
    }, index=years_future)
    res_df['Total_Projected'] = res_df['CVRJ_Baseline'] + res_df['Culpeper_Add']
    
    print("\nProjected Capacity Usage:")
    print(res_df)
    
    plt.figure(figsize=(10,6))
    plt.plot(res_df.index, res_df['Total_Projected'], label='Projected Total (CVRJ + Culpeper)', marker='o')
    plt.plot(res_df.index, res_df['CVRJ_Baseline'], label='CVRJ Baseline', linestyle='--')
    plt.axhline(y=660, color='r', linestyle='-', label='Max Capacity (660)')
    plt.title('CVRJ Capacity Forecast with Culpeper Integration')
    plt.legend()
    plt.grid(True)
    plt.show()

## Forecast Model Implementation
The following code processes the raw booking data to calculate ADP, loads census data, and performs SARIMA forecasting.

In [ ]:

import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
import matplotlib.pyplot as plt
import os

# --- Configuration ---
# Update paths to be relative to the notebook or absolute
# Assuming notebook is in cvrj-bed-forecasting/ForecastBedData/
DATA_DIR = "." 
CVRJ_FILE = "cvrj_dataset_v2.csv" # In same dir as notebook usually or parent?
# Check specific file location:
if not os.path.exists(CVRJ_FILE):
    # Try absolute path if relative fails, or parent
    CVRJ_FILE = "../cvrj_dataset_v2.csv"
    DATA_DIR = "."

print(f"Using CVRJ File: {CVRJ_FILE}")

# --- 1. Load and Process CVRJ Data ---
df_cvrj = pd.read_csv(CVRJ_FILE)
df_cvrj['Book Date'] = pd.to_datetime(df_cvrj['Book Date'], errors='coerce')
df_cvrj['Release Date'] = pd.to_datetime(df_cvrj['Release Date'], errors='coerce')

# Filter for relevant years (2012-2025)
df_cvrj = df_cvrj[df_cvrj['Book Date'].dt.year >= 2012]

# Calculate Daily Census (ADP)
min_date = df_cvrj['Book Date'].min()
max_date = df_cvrj['Release Date'].max()
if pd.isnull(max_date) or max_date.year > 2030: 
    max_date = pd.Timestamp('2025-12-31')

date_range = pd.date_range(start=min_date.normalize(), end=max_date.normalize(), freq='D')

events = []
for _, row in df_cvrj.iterrows():
    start = row['Book Date']
    end = row['Release Date']
    if pd.isnull(start): continue
    if pd.isnull(end): end = max_date
    start_date = start.normalize()
    end_date = end.normalize()
    if end_date < start_date: continue
    events.append((start_date, 1))
    events.append((end_date + pd.Timedelta(days=1), -1))

evt_df = pd.DataFrame(events, columns=['Date', 'Change'])
if not evt_df.empty:
    evt_df = evt_df.groupby('Date')['Change'].sum().sort_index()
    daily_census = evt_df.reindex(date_range, fill_value=0).cumsum()
else:
    daily_census = pd.Series(0, index=date_range)

# Aggregating to Annual ADP
annual_cvrj_adp = daily_census.resample('Y').mean()
print("CVRJ Annual ADP (Head):")
print(annual_cvrj_adp.head())

# --- 2. Load Population Data ---
counties = ['Fluvanna', 'Greene', 'Louisa', 'Madison', 'Orange']
pop_data = {}

for county in counties:
    fpath = os.path.join(DATA_DIR, f"{county}Population.csv")
    try:
        if os.path.exists(fpath):
            temp_df = pd.read_csv(fpath, header=4)
            target_row = temp_df.iloc[1]
            years = [str(y) for y in range(2012, 2025)]
            pop_series = target_row[years].str.replace(',', '').astype(float)
            pop_series.index = pd.to_datetime(pop_series.index, format='%Y')
            pop_data[county] = pop_series
        else:
            print(f"Warning: {fpath} not found.")
    except Exception as e:
        print(f"Error loading {county}: {e}")

if pop_data:
    total_cvrj_pop = pd.DataFrame(pop_data).sum(axis=1)
    total_cvrj_pop.index = total_cvrj_pop.index + pd.offsets.YearEnd()
else:
    total_cvrj_pop = pd.Series()

# --- 3. Load Culpeper Data ---
culpeper_data = {
    '2020': 148.93, '2021': 185.75, '2022': 210.82, 
    '2023': 200.24, '2024': 312.33, '2025': 227.81
}
culpeper_adp = pd.Series(culpeper_data)
culpeper_adp.index = pd.to_datetime(culpeper_adp.index, format='%Y') + pd.offsets.YearEnd()

# Culpeper Census
culp_pop_file = os.path.join(DATA_DIR, "CulpeperPopulation.csv")
culp_pop = pd.Series()
if os.path.exists(culp_pop_file):
    try:
        temp_culp = pd.read_csv(culp_pop_file, header=4)
        culp_pop_row = temp_culp.iloc[1]
        years = [str(y) for y in range(2012, 2025)]
        culp_pop = culp_pop_row[years].str.replace(',', '').astype(float)
        culp_pop.index = pd.to_datetime(culp_pop.index, format='%Y') + pd.offsets.YearEnd()
    except Exception as e:
        print(f"Error loading Culpeper Census: {e}")

# --- 4. SARIMA Modeling & Forecasting ---

def fit_forecast(adp_series, exog_series, name, steps=10):
    print(f"\nModeling {name}...")
    combined = pd.concat([adp_series, exog_series], axis=1).dropna()
    combined.columns = ['ADP', 'Pop']
    
    if combined.empty:
        print(f"Empty training data for {name}")
        return None, None
        
    try:
        model = SARIMAX(combined['ADP'], exog=combined['Pop'], order=(1,1,1), seasonal_order=(0,0,0,0))
        results = model.fit(disp=False)
        print(results.summary())
        
        # Forecast Population (Linear Trend)
        pop_y = combined['Pop'].values
        pop_x = np.arange(len(pop_y))
        z = np.polyfit(pop_x, pop_y, 1)
        p = np.poly1d(z)
        future_x = np.arange(len(pop_y), len(pop_y) + steps)
        future_pop = p(future_x)
        
        forecast = results.get_forecast(steps=steps, exog=future_pop.reshape(-1,1))
        forecast_vals = forecast.predicted_mean
        return forecast_vals, future_pop
    except Exception as e:
        print(f"Error modeling {name}: {e}")
        return None, None

# Model CVRJ
if not total_cvrj_pop.empty:
    # Extrapolate Pop 2025
    last_pop = total_cvrj_pop.iloc[-1]
    prev_pop = total_cvrj_pop.iloc[-2]
    total_cvrj_pop.loc[pd.Timestamp('2025-12-31')] = last_pop + (last_pop - prev_pop)

cvrj_forecast, cvrj_fut_pop = fit_forecast(annual_cvrj_adp, total_cvrj_pop, "CVRJ")

# Model Culpeper
if not culp_pop.empty:
    last_c_pop = culp_pop.iloc[-1]
    prev_c_pop = culp_pop.iloc[-2]
    culp_pop.loc[pd.Timestamp('2025-12-31')] = last_c_pop + (last_c_pop - prev_c_pop)

culpeper_clean = culpeper_adp[~culpeper_adp.index.year.isin([2020, 2021])]
culpeper_forecast, culp_fut_pop = fit_forecast(culpeper_clean, culp_pop, "Culpeper")

# --- 5. Visualization ---
if cvrj_forecast is not None and culpeper_forecast is not None:
    years_future = pd.date_range(start='2026-12-31', periods=10, freq='Y')
    res_df = pd.DataFrame({
        'CVRJ_Baseline': cvrj_forecast.values,
        'Culpeper_Add': culpeper_forecast.values
    }, index=years_future)
    res_df['Total_Projected'] = res_df['CVRJ_Baseline'] + res_df['Culpeper_Add']
    
    print("\nProjected Capacity Usage:")
    print(res_df)
    
    plt.figure(figsize=(10,6))
    plt.plot(res_df.index, res_df['Total_Projected'], label='Projected Total (CVRJ + Culpeper)', marker='o')
    plt.plot(res_df.index, res_df['CVRJ_Baseline'], label='CVRJ Baseline', linestyle='--')
    plt.axhline(y=660, color='r', linestyle='-', label='Max Capacity (660)')
    plt.title('CVRJ Capacity Forecast with Culpeper Integration')
    plt.legend()
    plt.grid(True)
    plt.show()

## Forecast Model Implementation
The following code processes the raw booking data to calculate ADP, loads census data, and performs SARIMA forecasting.

In [ ]:

import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
import matplotlib.pyplot as plt
import os

# --- Configuration ---
# Update paths to be relative to the notebook or absolute
# Assuming notebook is in cvrj-bed-forecasting/ForecastBedData/
DATA_DIR = "." 
CVRJ_FILE = "cvrj_dataset_v2.csv" # In same dir as notebook usually or parent?
# Check specific file location:
if not os.path.exists(CVRJ_FILE):
    # Try absolute path if relative fails, or parent
    CVRJ_FILE = "../cvrj_dataset_v2.csv"
    DATA_DIR = "."

print(f"Using CVRJ File: {CVRJ_FILE}")

# --- 1. Load and Process CVRJ Data ---
df_cvrj = pd.read_csv(CVRJ_FILE)
df_cvrj['Book Date'] = pd.to_datetime(df_cvrj['Book Date'], errors='coerce')
df_cvrj['Release Date'] = pd.to_datetime(df_cvrj['Release Date'], errors='coerce')

# Filter for relevant years (2012-2025)
df_cvrj = df_cvrj[df_cvrj['Book Date'].dt.year >= 2012]

# Calculate Daily Census (ADP)
min_date = df_cvrj['Book Date'].min()
max_date = df_cvrj['Release Date'].max()
if pd.isnull(max_date) or max_date.year > 2030: 
    max_date = pd.Timestamp('2025-12-31')

date_range = pd.date_range(start=min_date.normalize(), end=max_date.normalize(), freq='D')

events = []
for _, row in df_cvrj.iterrows():
    start = row['Book Date']
    end = row['Release Date']
    if pd.isnull(start): continue
    if pd.isnull(end): end = max_date
    start_date = start.normalize()
    end_date = end.normalize()
    if end_date < start_date: continue
    events.append((start_date, 1))
    events.append((end_date + pd.Timedelta(days=1), -1))

evt_df = pd.DataFrame(events, columns=['Date', 'Change'])
if not evt_df.empty:
    evt_df = evt_df.groupby('Date')['Change'].sum().sort_index()
    daily_census = evt_df.reindex(date_range, fill_value=0).cumsum()
else:
    daily_census = pd.Series(0, index=date_range)

# Aggregating to Annual ADP
annual_cvrj_adp = daily_census.resample('Y').mean()
print("CVRJ Annual ADP (Head):")
print(annual_cvrj_adp.head())

# --- 2. Load Population Data ---
counties = ['Fluvanna', 'Greene', 'Louisa', 'Madison', 'Orange']
pop_data = {}

for county in counties:
    fpath = os.path.join(DATA_DIR, f"{county}Population.csv")
    try:
        if os.path.exists(fpath):
            temp_df = pd.read_csv(fpath, header=4)
            target_row = temp_df.iloc[1]
            years = [str(y) for y in range(2012, 2025)]
            pop_series = target_row[years].str.replace(',', '').astype(float)
            pop_series.index = pd.to_datetime(pop_series.index, format='%Y')
            pop_data[county] = pop_series
        else:
            print(f"Warning: {fpath} not found.")
    except Exception as e:
        print(f"Error loading {county}: {e}")

if pop_data:
    total_cvrj_pop = pd.DataFrame(pop_data).sum(axis=1)
    total_cvrj_pop.index = total_cvrj_pop.index + pd.offsets.YearEnd()
else:
    total_cvrj_pop = pd.Series()

# --- 3. Load Culpeper Data ---
culpeper_data = {
    '2020': 148.93, '2021': 185.75, '2022': 210.82, 
    '2023': 200.24, '2024': 312.33, '2025': 227.81
}
culpeper_adp = pd.Series(culpeper_data)
culpeper_adp.index = pd.to_datetime(culpeper_adp.index, format='%Y') + pd.offsets.YearEnd()

# Culpeper Census
culp_pop_file = os.path.join(DATA_DIR, "CulpeperPopulation.csv")
culp_pop = pd.Series()
if os.path.exists(culp_pop_file):
    try:
        temp_culp = pd.read_csv(culp_pop_file, header=4)
        culp_pop_row = temp_culp.iloc[1]
        years = [str(y) for y in range(2012, 2025)]
        culp_pop = culp_pop_row[years].str.replace(',', '').astype(float)
        culp_pop.index = pd.to_datetime(culp_pop.index, format='%Y') + pd.offsets.YearEnd()
    except Exception as e:
        print(f"Error loading Culpeper Census: {e}")

# --- 4. SARIMA Modeling & Forecasting ---

def fit_forecast(adp_series, exog_series, name, steps=10):
    print(f"\nModeling {name}...")
    combined = pd.concat([adp_series, exog_series], axis=1).dropna()
    combined.columns = ['ADP', 'Pop']
    
    if combined.empty:
        print(f"Empty training data for {name}")
        return None, None
        
    try:
        model = SARIMAX(combined['ADP'], exog=combined['Pop'], order=(1,1,1), seasonal_order=(0,0,0,0))
        results = model.fit(disp=False)
        print(results.summary())
        
        # Forecast Population (Linear Trend)
        pop_y = combined['Pop'].values
        pop_x = np.arange(len(pop_y))
        z = np.polyfit(pop_x, pop_y, 1)
        p = np.poly1d(z)
        future_x = np.arange(len(pop_y), len(pop_y) + steps)
        future_pop = p(future_x)
        
        forecast = results.get_forecast(steps=steps, exog=future_pop.reshape(-1,1))
        forecast_vals = forecast.predicted_mean
        return forecast_vals, future_pop
    except Exception as e:
        print(f"Error modeling {name}: {e}")
        return None, None

# Model CVRJ
if not total_cvrj_pop.empty:
    # Extrapolate Pop 2025
    last_pop = total_cvrj_pop.iloc[-1]
    prev_pop = total_cvrj_pop.iloc[-2]
    total_cvrj_pop.loc[pd.Timestamp('2025-12-31')] = last_pop + (last_pop - prev_pop)

cvrj_forecast, cvrj_fut_pop = fit_forecast(annual_cvrj_adp, total_cvrj_pop, "CVRJ")

# Model Culpeper
if not culp_pop.empty:
    last_c_pop = culp_pop.iloc[-1]
    prev_c_pop = culp_pop.iloc[-2]
    culp_pop.loc[pd.Timestamp('2025-12-31')] = last_c_pop + (last_c_pop - prev_c_pop)

culpeper_clean = culpeper_adp[~culpeper_adp.index.year.isin([2020, 2021])]
culpeper_forecast, culp_fut_pop = fit_forecast(culpeper_clean, culp_pop, "Culpeper")

# --- 5. Visualization ---
if cvrj_forecast is not None and culpeper_forecast is not None:
    years_future = pd.date_range(start='2026-12-31', periods=10, freq='Y')
    res_df = pd.DataFrame({
        'CVRJ_Baseline': cvrj_forecast.values,
        'Culpeper_Add': culpeper_forecast.values
    }, index=years_future)
    res_df['Total_Projected'] = res_df['CVRJ_Baseline'] + res_df['Culpeper_Add']
    
    print("\nProjected Capacity Usage:")
    print(res_df)
    
    plt.figure(figsize=(10,6))
    plt.plot(res_df.index, res_df['Total_Projected'], label='Projected Total (CVRJ + Culpeper)', marker='o')
    plt.plot(res_df.index, res_df['CVRJ_Baseline'], label='CVRJ Baseline', linestyle='--')
    plt.axhline(y=660, color='r', linestyle='-', label='Max Capacity (660)')
    plt.title('CVRJ Capacity Forecast with Culpeper Integration')
    plt.legend()
    plt.grid(True)
    plt.show()

## Forecast Model Implementation
The following code processes the raw booking data to calculate ADP, loads census data, and performs SARIMA forecasting.

In [ ]:

import pandas as pd
import numpy as np
from statsmodels.tsa.statespace.sarimax import SARIMAX
import matplotlib.pyplot as plt
import os

# --- Configuration ---
# Update paths to be relative to the notebook or absolute
# Assuming notebook is in cvrj-bed-forecasting/ForecastBedData/
DATA_DIR = "." 
CVRJ_FILE = "cvrj_dataset_v2.csv" # In same dir as notebook usually or parent?
# Check specific file location:
if not os.path.exists(CVRJ_FILE):
    # Try absolute path if relative fails, or parent
    CVRJ_FILE = "../cvrj_dataset_v2.csv"
    DATA_DIR = "."

print(f"Using CVRJ File: {CVRJ_FILE}")

# --- 1. Load and Process CVRJ Data ---
df_cvrj = pd.read_csv(CVRJ_FILE)
df_cvrj['Book Date'] = pd.to_datetime(df_cvrj['Book Date'], errors='coerce')
df_cvrj['Release Date'] = pd.to_datetime(df_cvrj['Release Date'], errors='coerce')

# Filter for relevant years (2012-2025)
df_cvrj = df_cvrj[df_cvrj['Book Date'].dt.year >= 2012]

# Calculate Daily Census (ADP)
min_date = df_cvrj['Book Date'].min()
max_date = df_cvrj['Release Date'].max()
if pd.isnull(max_date) or max_date.year > 2030: 
    max_date = pd.Timestamp('2025-12-31')

date_range = pd.date_range(start=min_date.normalize(), end=max_date.normalize(), freq='D')

events = []
for _, row in df_cvrj.iterrows():
    start = row['Book Date']
    end = row['Release Date']
    if pd.isnull(start): continue
    if pd.isnull(end): end = max_date
    start_date = start.normalize()
    end_date = end.normalize()
    if end_date < start_date: continue
    events.append((start_date, 1))
    events.append((end_date + pd.Timedelta(days=1), -1))

evt_df = pd.DataFrame(events, columns=['Date', 'Change'])
if not evt_df.empty:
    evt_df = evt_df.groupby('Date')['Change'].sum().sort_index()
    daily_census = evt_df.reindex(date_range, fill_value=0).cumsum()
else:
    daily_census = pd.Series(0, index=date_range)

# Aggregating to Annual ADP
annual_cvrj_adp = daily_census.resample('Y').mean()
print("CVRJ Annual ADP (Head):")
print(annual_cvrj_adp.head())

# --- 2. Load Population Data ---
counties = ['Fluvanna', 'Greene', 'Louisa', 'Madison', 'Orange']
pop_data = {}

for county in counties:
    fpath = os.path.join(DATA_DIR, f"{county}Population.csv")
    try:
        if os.path.exists(fpath):
            temp_df = pd.read_csv(fpath, header=4)
            target_row = temp_df.iloc[1]
            years = [str(y) for y in range(2012, 2025)]
            pop_series = target_row[years].str.replace(',', '').astype(float)
            pop_series.index = pd.to_datetime(pop_series.index, format='%Y')
            pop_data[county] = pop_series
        else:
            print(f"Warning: {fpath} not found.")
    except Exception as e:
        print(f"Error loading {county}: {e}")

if pop_data:
    total_cvrj_pop = pd.DataFrame(pop_data).sum(axis=1)
    total_cvrj_pop.index = total_cvrj_pop.index + pd.offsets.YearEnd()
else:
    total_cvrj_pop = pd.Series()

# --- 3. Load Culpeper Data ---
culpeper_data = {
    '2020': 148.93, '2021': 185.75, '2022': 210.82, 
    '2023': 200.24, '2024': 312.33, '2025': 227.81
}
culpeper_adp = pd.Series(culpeper_data)
culpeper_adp.index = pd.to_datetime(culpeper_adp.index, format='%Y') + pd.offsets.YearEnd()

# Culpeper Census
culp_pop_file = os.path.join(DATA_DIR, "CulpeperPopulation.csv")
culp_pop = pd.Series()
if os.path.exists(culp_pop_file):
    try:
        temp_culp = pd.read_csv(culp_pop_file, header=4)
        culp_pop_row = temp_culp.iloc[1]
        years = [str(y) for y in range(2012, 2025)]
        culp_pop = culp_pop_row[years].str.replace(',', '').astype(float)
        culp_pop.index = pd.to_datetime(culp_pop.index, format='%Y') + pd.offsets.YearEnd()
    except Exception as e:
        print(f"Error loading Culpeper Census: {e}")

# --- 4. SARIMA Modeling & Forecasting ---

def fit_forecast(adp_series, exog_series, name, steps=10):
    print(f"\nModeling {name}...")
    combined = pd.concat([adp_series, exog_series], axis=1).dropna()
    combined.columns = ['ADP', 'Pop']
    
    if combined.empty:
        print(f"Empty training data for {name}")
        return None, None
        
    try:
        model = SARIMAX(combined['ADP'], exog=combined['Pop'], order=(1,1,1), seasonal_order=(0,0,0,0))
        results = model.fit(disp=False)
        print(results.summary())
        
        # Forecast Population (Linear Trend)
        pop_y = combined['Pop'].values
        pop_x = np.arange(len(pop_y))
        z = np.polyfit(pop_x, pop_y, 1)
        p = np.poly1d(z)
        future_x = np.arange(len(pop_y), len(pop_y) + steps)
        future_pop = p(future_x)
        
        forecast = results.get_forecast(steps=steps, exog=future_pop.reshape(-1,1))
        forecast_vals = forecast.predicted_mean
        return forecast_vals, future_pop
    except Exception as e:
        print(f"Error modeling {name}: {e}")
        return None, None

# Model CVRJ
if not total_cvrj_pop.empty:
    # Extrapolate Pop 2025
    last_pop = total_cvrj_pop.iloc[-1]
    prev_pop = total_cvrj_pop.iloc[-2]
    total_cvrj_pop.loc[pd.Timestamp('2025-12-31')] = last_pop + (last_pop - prev_pop)

cvrj_forecast, cvrj_fut_pop = fit_forecast(annual_cvrj_adp, total_cvrj_pop, "CVRJ")

# Model Culpeper
if not culp_pop.empty:
    last_c_pop = culp_pop.iloc[-1]
    prev_c_pop = culp_pop.iloc[-2]
    culp_pop.loc[pd.Timestamp('2025-12-31')] = last_c_pop + (last_c_pop - prev_c_pop)

culpeper_clean = culpeper_adp[~culpeper_adp.index.year.isin([2020, 2021])]
culpeper_forecast, culp_fut_pop = fit_forecast(culpeper_clean, culp_pop, "Culpeper")

# --- 5. Visualization ---
if cvrj_forecast is not None and culpeper_forecast is not None:
    years_future = pd.date_range(start='2026-12-31', periods=10, freq='Y')
    res_df = pd.DataFrame({
        'CVRJ_Baseline': cvrj_forecast.values,
        'Culpeper_Add': culpeper_forecast.values
    }, index=years_future)
    res_df['Total_Projected'] = res_df['CVRJ_Baseline'] + res_df['Culpeper_Add']
    
    print("\nProjected Capacity Usage:")
    print(res_df)
    
    plt.figure(figsize=(10,6))
    plt.plot(res_df.index, res_df['Total_Projected'], label='Projected Total (CVRJ + Culpeper)', marker='o')
    plt.plot(res_df.index, res_df['CVRJ_Baseline'], label='CVRJ Baseline', linestyle='--')
    plt.axhline(y=660, color='r', linestyle='-', label='Max Capacity (660)')
    plt.title('CVRJ Capacity Forecast with Culpeper Integration')
    plt.legend()
    plt.grid(True)
    plt.show()